---
title: Carrie Morris
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@carriemorris.me
description: Digital design and illustration
baseurl: ''
url: ''
twitter_username: carriemoja
github_username: carrie88
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
paginate: 5
permalink: pretty
